### PR TITLE
[FIX] industry_real_estate: replace kanban-box with card

### PR DESCRIPTION
**Pull request by dhrs-odoo**
In this PR as kanban-box is deprecated so we have replaced it with the card

### CODE REVIEW

**Review by vava-odoo — CHANGES_REQUESTED** [review]
Yes, runbot is green, but the structure must be improved accordingly.
Before:
image
With your PR:
image

EDIT: looking twice, none is fine. Could you take a bit of time to clean this view? Thanks!

**Comment by dhrs-odoo** [comment]
Hello @vava-odoo 
I have made the changes 
Can You have a look at it once you are free
Thank You :innocent:

**Review by vava-odoo — APPROVED** [review]
Better!
I made a small commit to fix the alignment and remove useless class. If you approve, you can squash the commits :-)

**Comment by dhrs-odoo** [comment]
Hello @vava-odoo 
It looks good to me 
I have squashed the commits 
Thank You :innocent:

**Comment by vava-odoo** [comment]
@robodoo r+

**Comment by vava-odoo** [comment]
@robodoo r+

**Comment by vava-odoo** [comment]
@robodoo r-

**Pull request closed without merging**
