### PR TITLE
[FIX] certification_organism: demo data conflict with normal demo

### PR DESCRIPTION
**Pull request by zepa-odoo**
Fix hr leave validation error.

### CODE REVIEW

**Review by jva-odoo — APPROVED** [review]

**Comment by vava-odoo** [comment]
Hello @zepa-odoo 
I did a quick fix already on this: https://github.com/odoo/industry/pull/49
But I'll discuss your fix with @pimodoo as I don't get why we need this `hr.leave`.
Cheers!

**Comment by zepa-odoo** [comment]
We need hr.leave as it is linked up with calendar_event, 
Clicking on the stat button in calendar event gives the details of sick leave therefore hr.leave is necessary to add in demo.

**Comment by jva-odoo** [comment]
@vava-odoo time-off is required as per demo data.
and this fix is archived time-off that conflicts with this.

giphy-downsized

**Comment by pimodoo** [comment]
fixed in https://github.com/odoo/industry/pull/49

**Pull request closed without merging**
